criterion:
  name: ce

optimizer:
  name: adamw
  lr: 0.0005
  weight_decay: 0.01

scheduler:
  name: cosine
  lr_min: 0.00002

run:
  experiment: "cifar10_vgg8_pretrain_NA"
  n_epochs: 200
  n_epochs_NA: 20
  batch_size: 64
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

quantize:
  quant_flag: True
  N_bits: 8
  N_bits_a: 8
  scaling_range_in: 1.
  scaling_range_out: 1.

noise:
  noise_flag: True
  noise_level: 0.005
  output_noise_level: 0.005
  weight_noise_std: 0.005 #For NA pre-training
  random_state: 42

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "cifar10/vgg8/pretrain_NA"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""

model:
  name: "SparseBP_GEMM_VGG8"
  mode: "defender"
  block_list: [8, 8]
  act: relu
  act_thres: 6
  norm: bn

debug:
  verbose: 1

